# Generated by Django 4.0.5 on 2022-08-16 19:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_orders_details_remove_orders_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pizza', '0008_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('phone', models.CharField(default='', max_length=200)),
                ('city', models.CharField(default='', max_length=200)),
                ('reserved', models.BooleanField(default=False)),
                ('user', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='customers',
            name='user',
        ),
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.DeleteModel(
            name='products',
        ),
        migrations.DeleteModel(
            name='customers',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
